### ISSUE TITLE
Verifier application not working

### ISSUE THREAD

**Issue by MosCD3** [bcgov/dts-vc-issuer-service#73]
I want to be able to verify the credential issued as the UI suggests but the "Verify Credential" button doesn't do anything !

**Comment by swcurran** [comment]
I'll have to look at this again.  As I recall, another verifier docker image needs to start, and I'm not sure it does.  PRs #67 and #70 implement the functionality.

Note that this app was built in just a couple of days, used for some demos and then not followed up on. It was done before the proof of vaccination approach was finalized, and their was demand for such a credential. When the work restarted, the Smart Health Card approach was used instead of VCs.
